config/routes.rb
Rails.application.routes.draw do

  root "items#index"
  resources :items do
    resources :bids, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base

  belongs_to :user
  belongs_to :item

  validates :bid_amount, presence: true
  default_scope { order("created_at DESC") }

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :user

  has_many :bids, dependent: :destroy

  validates :title,     presence: true
  validates :detail,    presence: true
  validates :end_date,  presence: true

  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :bids, dependent: :nullify

  validates :email_address, presence: true, uniqueness: true,
                    format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}".strip
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, notice: "please sign in" unless user_signed_in?
  end

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def sign_in(user)
    session[:user_id] = user.id
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  before_action :authenticate_user!

  def create

    @item     = Item.find params[:item_id]
    
    @bid      = Bid.new bid_params
    @bid.item = @item
    @bid.user = current_user


    if @bid.save
      redirect_to item_path(@item), notice: "Bid submitted!"
    else
      flash[:alert] = "Comment not added"
      render "/items/show"
    end
  end

  private

  def bid_params
    params.require(:bid).permit(:bid_amount)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_item, only: [:show, :edit, :update, :destroy]


  def index
    @items = Item.all
  end

  def show
    @bid = Bid.new
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create

    @item = Item.new(item_params)
    @item.user = current_user

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_price
      self.school = "my school" if self.school.blank?
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :detail, :end_date, :reserved_price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email_address params[:email_address]
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user_id
      redirect_to new_user_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit([:email_address, :password, :password_confirmtion])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>

  <div class="field">
    If you would like to enter a reserver price please do so. If not, bidding will start at $1.00
    <%= f.label :reserved_price %><br>
    <%= f.number_field :reserved_price, :step => 0.01 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Detail</th>
      <th>End date</th>
      <th>Price</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.detail %></td>
        <td><%= item.end_date %></td>
        <td>
          <% if item.reserved_price == 1.0 %>
            <%= number_to_currency(item.reserved_price) %>
          <% else %>
            Reserve Not Yet met!
          <% end %>
        </td>
        <td><%= item.user(item.user_id).email_address %></td>
        <td><%= link_to 'Show', item %></td>
        <% if current_user.id == item.user_id %>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @item.detail %>
</p>

<p>
  <strong>End date:</strong>
  <%= @item.end_date %>
</p>

<p>
  <% if @item.reserved_price == 1.0 %>
    <strong>Price:</strong>
    <%= number_to_currency(@item.reserved_price) %>
  <% else %>
    <strong>Price:</strong>
    Reserve Not Yet met!
  <% end %>
</p>

<p>
  <strong>User:</strong>
  <%= @item.user(@item.user_id).email_address %>
</p>
<% if current_user.id == @item.user_id %>
  <%= link_to 'Edit', edit_item_path(@item) %> |
  <% end %>
<%= link_to 'Back', items_path %>

<hr>

<% if current_user.id != @item.user_id %>
<h2>place a bid</h2>
  <% if @bid.errors.any? %>
    <ul>
      <% @bid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for [@item, @bid] do |f| %>
    <div class="form-group">
      <%= f.label :bid_amount %>
      <%= f.text_field :bid_amount, class: "form-control" %>
    </div>
    <%= f.submit "bid", class: "btn btn-primary" %>
  <% end %>
<% end %>
<h2>Bids</h2>
<% @item.bids.each do |bids| %>
  <div class="well" id="<%= dom_id(bids) %>">
    Bid: <%= number_to_currency(bids.bid_amount) %>&nbsp; &nbsp;
    by: <%= bids.user(bids.user_id).email_address %><br><br>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wanna be EBAY!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "home", root_path %>
  <% if user_signed_in? %>
    Hello <%= current_user.email_address %>,
    <%= link_to "New Items", new_item_path %>
    <%= link_to "Logout", sessions_path, method: :delete,
      data: {confirm: "are you sure you want to log out?"}%>
    <% else %>
      <%= link_to "Login", new_session_path %> |
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
<hr>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @user do |f| %>
  <div>
    <%= f.label :email_address %>
    <%= f.email_field :email_address %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>
<%= render "form" %>